# Generated by Django 4.2.7 on 2023-11-28 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_storage_product_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 11, 28, 8, 21, 43, 129483, tzinfo=datetime.timezone.utc), max_length=250),
            preserve_default=False,
        ),
    ]
