# Generated by Django 4.2.6 on 2023-11-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
