# Generated by Django 4.2.6 on 2023-11-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_delete_tag_remove_problem_taggits_alter_problem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
    ]
