# Generated by Django 4.2.7 on 2023-11-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teachers', to='teachers.roles'),
        ),
    ]
