# Generated by Django 4.2.7 on 2023-11-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer_full_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('target', models.CharField(max_length=250)),
                ('direction', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
