# Generated by Django 4.2.7 on 2023-11-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_orders_products_remove_orders_user_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.orders'),
        ),
    ]
