# Generated by Django 4.2.7 on 2023-11-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('main', '0005_cartitems_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='products',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
