# Generated by Django 4.2.7 on 2023-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartitems_products_cartitems_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='main.cartitems'),
        ),
    ]
