# Generated by Django 4.2.7 on 2023-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_surname_orders_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.cartitems'),
        ),
    ]
