# Generated by Django 4.2.7 on 2023-12-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
