# Generated by Django 4.2.7 on 2023-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
