# Generated by Django 4.2.7 on 2023-11-13 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_groups'),
        ('students', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('time', models.CharField(max_length=200)),
                ('started_date', models.DateField()),
                ('ends_in', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='groups.room')),
                ('teacher_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher', to='teachers.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
