# Generated by Django 4.2.7 on 2023-11-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=200)),
                ('added_time', models.DateField(auto_now_add=True)),
                ('group', models.ManyToManyField(blank=True, related_name='students', to='groups.groups')),
            ],
        ),
    ]
