# Generated by Django 4.2.7 on 2023-11-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('students', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='main.staff'),
        ),
    ]
