# Generated by Django 4.2.7 on 2023-11-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_couse_of_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandence',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
