# Generated by Django 4.2.7 on 2023-11-17 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_attandence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attandence',
            name='student',
        ),
        migrations.AddField(
            model_name='attandence',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attandence', to='students.students'),
            preserve_default=False,
        ),
    ]
