# Generated by Django 4.2.7 on 2023-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_attandence_student_attandence_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandence',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
