# Generated by Django 4.2.7 on 2023-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_attandence_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandence',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
