# Generated by Django 4.2.7 on 2023-11-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_attandence_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
