# Generated by Django 4.2.7 on 2023-11-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_payment_date_added_alter_payment_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='staff',
        ),
    ]
