# Generated by Django 4.2.7 on 2023-11-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_payment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='economical_status',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
