# Generated by Django 4.2.7 on 2023-11-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_students_economical_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
