# Generated by Django 4.2.7 on 2023-11-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_students_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='economical_status',
            field=models.BooleanField(default=False),
        ),
    ]
