# Generated by Django 4.2.7 on 2023-11-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_durationcourse_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course_start_year',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start_year',
        ),
        migrations.DeleteModel(
            name='DurationCourse',
        ),
    ]
