# Generated by Django 4.2.7 on 2023-11-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_attendance_attandence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attandence',
            field=models.CharField(choices=[('Du', 'Dushanba'), ('se', 'Seshanba')], max_length=40),
        ),
    ]
