# Generated by Django 4.2.7 on 2023-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('added_text_message', models.DateTimeField(auto_now=True)),
                ('from_who', models.CharField(max_length=200)),
                ('to_who', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
